services:
  - docker
    
before_install:
  - docker build -t myimage/docker-react .

script:
  - docker run -d -p 80:80 myimage/docker-react 

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker"
  env: "Docker-env-1"
  bucket_name: "elasticbeanstalk-eu-central-1-712243451067"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY


