#sudo: required
services:
    - docker
    
before_install:
    - docker build -t myimage/docker-react -f Dockerfile.dev .

script:
    - docker run myimage/docker-react npm run test -- --coverage




